LogCategory = "2"
LogReference = ""
CurrentDirectory = ""
FetchMasterBrokerId = "4"

SGB_Status_Fetch_Count = "15"

SGB_StartTime = "00:00:00"
SGB_EndTime = "23:59:59"
SGB_CloseTime = "15:30:00"

#to restrict the quantity in SGB
SGB_MAXQUANTITY = "4000"