#IPO Controlls
IPO_ShowDiscount = "Y"
IPO_CancelAllowed = "Y"
IPO_ModifyAllowed = "Y"

#IPO Display texts
IPO_MasterNoDataText = "No IPO are open for sale currently !!."
IPO_HistoryNoDataText = "You haven't invested in any IPOs."

#Replace the d with the corresponding symbol
IPO_DiscountText = "Discount (d)"

IPO_InfoText = "IPO window will remain open from 10 AM till 5 PM.However your may apply after 5PM as offline.IPO can be modified only between 10 AM to 5 PM"

#Replace the 0 with the corresponding IssueSize

IPO_SmeText = "This stock belongs to the SME (Small and Medium enterprises) segment which usually has low liquidity and is hence also riskier. It will be traded in a lot size of 0 shares after listing. Selling in secondary market post listing is subjective to the RMS policy of FLATTRADE. Please refer RMS policy for more details."

IPO_PolicyText = "I hereby undertake that I have read the Red Herring Prospectus and I am an eligible UPI bidder as per the application provisions of the SEBI (Issue of Capital and Disclosure Requirement) Regulation, 2009. " 

#Configuration For Specific Clients
IPO_Specific_Client = "FT000069"