#----------------------------------------------------------------
#IPO
#----------------------------------------------------------------

IPO_ClientEmail_Subject = "IPO Order"

IPO_ClientEmail_html = "html/IpoOrderTemplate.html"

#----------------------------------------------------------------
#SGB
#----------------------------------------------------------------

SGB_ClientEmail_Subject = "SGB Order"

#commented by pavithra
#SGB_VerifyFund_html = "html/VerifyClientFund.html"
SGB_VerifyFOFund_html = "html/VerifyClientFund.html"

SGB_BlockClientFund_html = "html/BlockClientMail.html"

SGB_InsufficientAmt_html = "html/InsufficientAmount.html"

SGB_SuccessOrderMail_html = "html/Exchagestatus.html"

SGB_OrderSuccess_html = "html/SgbOrderTemplate.html"

SGB_RPBO_Failed_Mail_html = "html/ReverseProcessFailed.html"

SGB_RPBO_SUCCESS_Mail_html = "html/RpSuccess.html"

SGB_RPFO_Failed_Mail_html = "html/RpFrontoffice.html"






